<?php

// autoload_namespaces.php generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'RESTful' => $vendorDir . '/bninja/restful/src',
    'Httpful' => $vendorDir . '/nategood/httpful/src',
    'Balanced' => $vendorDir . '/balanced/balanced/src',
);
